--DDL Commands - (CARDT) CREATE, ALTER, RENAME, DROP, TRUNCATE

--Create table

CREATE TABLE SUTHERLAND(
NAME VARCHAR2(30),
DEPT CHAR(5),
AGE NUMBER,
SALARY NUMBER);

--Describe table

DESC SUTHERLAND; / DESCRIBE SUTHERLAND;

--Insert values

INSERT INTO SUTHERLAND VALUES('Pamitha','CS-ch',22,20000);
INSERT INTO SUTHERLAND VALUES('Swetha','CS-ch',21,18000);
INSERT INTO SUTHERLAND VALUES('Pragathy','CS-ch',23,19000);
INSERT INTO SUTHERLAND VALUES('Dinesh','CS-ch',24,19000);
INSERT INTO SUTHERLAND VALUES('Kamatchi','CS-ch',25,20000);

INSERT INTO SUTHERLAND (NAME, AGE) VALUES('Divya',22);

INSERT INTO SUTHERLAND (NAME, DEPT) VALUES('Rahul','CS-ch');

--Display table

SELECT * FROM SUTHERLAND;

SELECT NAME,SALARY FROM SUTHERLAND;

--Datatypes and varchar2 vs char

STRING - VARCHAR2, CHAR
NUMERIC - NUMBER

VARCHAR2 - SIZE 10 - 10 OR MORE THAN 10
CHAR - SIZE 10 - 10 OR BELOW 10



